from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 650)
        MainWindow.setMinimumSize(QtCore.QSize(900, 650))
        MainWindow.setMaximumSize(QtCore.QSize(900, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\imgs/logo_engenharia.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, -15, 900, 615))
        self.stackedWidget.setMinimumSize(QtCore.QSize(900, 615))
        self.stackedWidget.setMaximumSize(QtCore.QSize(900, 615))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.info = QtWidgets.QLabel(self.home)
        self.info.setGeometry(QtCore.QRect(160, 245, 581, 111))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.info.setFont(font)
        self.info.setObjectName("info")
        self.logo = QtWidgets.QLabel(self.home)
        self.logo.setGeometry(QtCore.QRect(335, 210, 230, 50))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(".\\imgs/logo_univates.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.stackedWidget.addWidget(self.home)
        self.mccabe = QtWidgets.QWidget()
        self.mccabe.setObjectName("mccabe")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mccabe)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_calc = QtWidgets.QFrame(self.mccabe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_calc.sizePolicy().hasHeightForWidth())
        self.frame_calc.setSizePolicy(sizePolicy)
        self.frame_calc.setMinimumSize(QtCore.QSize(434, 597))
        self.frame_calc.setMaximumSize(QtCore.QSize(434, 597))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_calc.setFont(font)
        self.frame_calc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_calc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_calc.setObjectName("frame_calc")
        self.radio_btn_parcial = QtWidgets.QRadioButton(self.frame_calc)
        self.radio_btn_parcial.setGeometry(QtCore.QRect(200, 115, 82, 17))
        self.radio_btn_parcial.setObjectName("radio_btn_parcial")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radio_btn_parcial)
        self.pa = QtWidgets.QLineEdit(self.frame_calc)
        self.pa.setGeometry(QtCore.QRect(120, 175, 113, 20))
        self.pa.setObjectName("pa")
        self.label_23 = QtWidgets.QLabel(self.frame_calc)
        self.label_23.setGeometry(QtCore.QRect(40, 180, 47, 13))
        self.label_23.setObjectName("label_23")
        self.radio_btn_valor = QtWidgets.QRadioButton(self.frame_calc)
        self.radio_btn_valor.setGeometry(QtCore.QRect(100, 115, 82, 17))
        self.radio_btn_valor.setObjectName("radio_btn_valor")
        self.buttonGroup_2.addButton(self.radio_btn_valor)
        self.btn_ideal = QtWidgets.QRadioButton(self.frame_calc)
        self.btn_ideal.setGeometry(QtCore.QRect(100, 35, 82, 17))
        self.btn_ideal.setObjectName("btn_ideal")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.btn_ideal)
        self.btn_non_ideal = QtWidgets.QRadioButton(self.frame_calc)
        self.btn_non_ideal.setGeometry(QtCore.QRect(200, 35, 82, 17))
        self.btn_non_ideal.setObjectName("btn_non_ideal")
        self.buttonGroup.addButton(self.btn_non_ideal)
        self.label_25 = QtWidgets.QLabel(self.frame_calc)
        self.label_25.setGeometry(QtCore.QRect(40, 150, 47, 16))
        self.label_25.setObjectName("label_25")
        self.pb = QtWidgets.QLineEdit(self.frame_calc)
        self.pb.setGeometry(QtCore.QRect(120, 205, 113, 20))
        self.pb.setObjectName("pb")
        self.alpha_vl = QtWidgets.QLineEdit(self.frame_calc)
        self.alpha_vl.setGeometry(QtCore.QRect(120, 145, 113, 20))
        self.alpha_vl.setObjectName("alpha_vl")
        self.label_26 = QtWidgets.QLabel(self.frame_calc)
        self.label_26.setGeometry(QtCore.QRect(40, 210, 47, 13))
        self.label_26.setObjectName("label_26")
        self.line_4 = QtWidgets.QFrame(self.frame_calc)
        self.line_4.setGeometry(QtCore.QRect(0, 250, 441, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_27 = QtWidgets.QLabel(self.frame_calc)
        self.label_27.setGeometry(QtCore.QRect(40, 355, 47, 13))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_calc)
        self.label_28.setGeometry(QtCore.QRect(40, 320, 47, 13))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame_calc)
        self.label_29.setGeometry(QtCore.QRect(240, 525, 81, 20))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_calc)
        self.label_30.setGeometry(QtCore.QRect(40, 425, 47, 13))
        self.label_30.setObjectName("label_30")
        self.btn_exec = QtWidgets.QPushButton(self.frame_calc)
        self.btn_exec.setGeometry(QtCore.QRect(310, 360, 75, 23))
        self.btn_exec.setObjectName("btn_exec")
        self.R = QtWidgets.QLineEdit(self.frame_calc)
        self.R.setGeometry(QtCore.QRect(120, 420, 113, 20))
        self.R.setObjectName("R")
        self.q_mccabe = QtWidgets.QLineEdit(self.frame_calc)
        self.q_mccabe.setGeometry(QtCore.QRect(120, 385, 113, 20))
        self.q_mccabe.setObjectName("q_mccabe")
        self.res_alimentacao = QtWidgets.QTextBrowser(self.frame_calc)
        self.res_alimentacao.setGeometry(QtCore.QRect(330, 520, 81, 31))
        self.res_alimentacao.setObjectName("res_alimentacao")
        self.label_31 = QtWidgets.QLabel(self.frame_calc)
        self.label_31.setGeometry(QtCore.QRect(40, 285, 47, 13))
        self.label_31.setObjectName("label_31")
        self.res_estagios = QtWidgets.QTextBrowser(self.frame_calc)
        self.res_estagios.setGeometry(QtCore.QRect(130, 520, 81, 31))
        self.res_estagios.setObjectName("res_estagios")
        self.label_32 = QtWidgets.QLabel(self.frame_calc)
        self.label_32.setGeometry(QtCore.QRect(40, 390, 47, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.frame_calc)
        self.label_33.setGeometry(QtCore.QRect(40, 525, 71, 20))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_calc)
        self.label_34.setGeometry(QtCore.QRect(10, 455, 111, 20))
        self.label_34.setObjectName("label_34")
        self.xD = QtWidgets.QDoubleSpinBox(self.frame_calc)
        self.xD.setGeometry(QtCore.QRect(120, 280, 113, 22))
        self.xD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.xD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xD.setDecimals(3)
        self.xD.setMinimum(0.0)
        self.xD.setMaximum(1.0)
        self.xD.setSingleStep(0.01)
        self.xD.setProperty("value", 0.0)
        self.xD.setObjectName("xD")
        self.xB = QtWidgets.QDoubleSpinBox(self.frame_calc)
        self.xB.setGeometry(QtCore.QRect(120, 315, 113, 22))
        self.xB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.xB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xB.setDecimals(3)
        self.xB.setMinimum(0.0)
        self.xB.setMaximum(1.0)
        self.xB.setSingleStep(0.01)
        self.xB.setProperty("value", 0.0)
        self.xB.setObjectName("xB")
        self.xF = QtWidgets.QDoubleSpinBox(self.frame_calc)
        self.xF.setGeometry(QtCore.QRect(120, 350, 113, 22))
        self.xF.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.xF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xF.setDecimals(3)
        self.xF.setMinimum(0.0)
        self.xF.setMaximum(1.0)
        self.xF.setSingleStep(0.01)
        self.xF.setProperty("value", 0.0)
        self.xF.setObjectName("xF")
        self.n_mur = QtWidgets.QDoubleSpinBox(self.frame_calc)
        self.n_mur.setGeometry(QtCore.QRect(120, 455, 113, 22))
        self.n_mur.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n_mur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.n_mur.setMinimum(0.01)
        self.n_mur.setMaximum(1.0)
        self.n_mur.setSingleStep(0.01)
        self.n_mur.setProperty("value", 1.0)
        self.n_mur.setObjectName("n_mur")
        self.save_fig = QtWidgets.QPushButton(self.frame_calc)
        self.save_fig.setGeometry(QtCore.QRect(330, 570, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_fig.setFont(font)
        self.save_fig.setObjectName("save_fig")
        self.qbox_n_ideal = QtWidgets.QComboBox(self.frame_calc)
        self.qbox_n_ideal.setGeometry(QtCore.QRect(260, 70, 150, 22))
        self.qbox_n_ideal.setObjectName("qbox_n_ideal")
        self.horizontalLayout.addWidget(self.frame_calc)
        self.line = QtWidgets.QFrame(self.mccabe)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.frame_graf = QtWidgets.QFrame(self.mccabe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_graf.sizePolicy().hasHeightForWidth())
        self.frame_graf.setSizePolicy(sizePolicy)
        self.frame_graf.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_graf.setMaximumSize(QtCore.QSize(433, 597))
        self.frame_graf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graf.setObjectName("frame_graf")
        self.horizontalLayout.addWidget(self.frame_graf)
        self.stackedWidget.addWidget(self.mccabe)
        self.fug = QtWidgets.QWidget()
        self.fug.setObjectName("fug")
        self.qtd_comps = QtWidgets.QSpinBox(self.fug)
        self.qtd_comps.setGeometry(QtCore.QRect(200, 80, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.qtd_comps.setFont(font)
        self.qtd_comps.setMinimum(2)
        self.qtd_comps.setMaximum(10)
        self.qtd_comps.setObjectName("qtd_comps")
        self.label = QtWidgets.QLabel(self.fug)
        self.label.setGeometry(QtCore.QRect(30, 80, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comps_num_qBox = QtWidgets.QComboBox(self.fug)
        self.comps_num_qBox.setGeometry(QtCore.QRect(30, 150, 150, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comps_num_qBox.setFont(font)
        self.comps_num_qBox.setObjectName("comps_num_qBox")
        self.comps_qBox = QtWidgets.QComboBox(self.fug)
        self.comps_qBox.setGeometry(QtCore.QRect(30, 210, 150, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comps_qBox.setFont(font)
        self.comps_qBox.setObjectName("comps_qBox")
        self.hk_rdbtn = QtWidgets.QRadioButton(self.fug)
        self.hk_rdbtn.setGeometry(QtCore.QRect(200, 160, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hk_rdbtn.setFont(font)
        self.hk_rdbtn.setObjectName("hk_rdbtn")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.hk_rdbtn)
        self.lk_rdbtn = QtWidgets.QRadioButton(self.fug)
        self.lk_rdbtn.setGeometry(QtCore.QRect(200, 130, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lk_rdbtn.setFont(font)
        self.lk_rdbtn.setObjectName("lk_rdbtn")
        self.buttonGroup_3.addButton(self.lk_rdbtn)
        self.F = QtWidgets.QLineEdit(self.fug)
        self.F.setGeometry(QtCore.QRect(290, 80, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.F.setFont(font)
        self.F.setText("")
        self.F.setObjectName("F")
        self.ref_ratio = QtWidgets.QLineEdit(self.fug)
        self.ref_ratio.setGeometry(QtCore.QRect(290, 130, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ref_ratio.setFont(font)
        self.ref_ratio.setObjectName("ref_ratio")
        self.q_fug = QtWidgets.QLineEdit(self.fug)
        self.q_fug.setGeometry(QtCore.QRect(290, 180, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.q_fug.setFont(font)
        self.q_fug.setObjectName("q_fug")
        self.Tbolha = QtWidgets.QLineEdit(self.fug)
        self.Tbolha.setGeometry(QtCore.QRect(480, 80, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Tbolha.setFont(font)
        self.Tbolha.setObjectName("Tbolha")
        self.Torvalho = QtWidgets.QLineEdit(self.fug)
        self.Torvalho.setGeometry(QtCore.QRect(480, 130, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Torvalho.setFont(font)
        self.Torvalho.setObjectName("Torvalho")
        self.label_2 = QtWidgets.QLabel(self.fug)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.fug)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_3 = QtWidgets.QFrame(self.fug)
        self.line_3.setGeometry(QtCore.QRect(0, 310, 901, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.preview_btn = QtWidgets.QPushButton(self.fug)
        self.preview_btn.setGeometry(QtCore.QRect(544, 250, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.preview_btn.setFont(font)
        self.preview_btn.setObjectName("preview_btn")
        self.calc_fug_btn = QtWidgets.QPushButton(self.fug)
        self.calc_fug_btn.setGeometry(QtCore.QRect(770, 250, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.calc_fug_btn.setFont(font)
        self.calc_fug_btn.setObjectName("calc_fug_btn")
        self.label_4 = QtWidgets.QLabel(self.fug)
        self.label_4.setGeometry(QtCore.QRect(290, 60, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.fug)
        self.label_5.setGeometry(QtCore.QRect(290, 110, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.fug)
        self.label_6.setGeometry(QtCore.QRect(290, 160, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.fug)
        self.label_7.setGeometry(QtCore.QRect(480, 60, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.fug)
        self.label_8.setGeometry(QtCore.QRect(480, 110, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.f_lk = QtWidgets.QDoubleSpinBox(self.fug)
        self.f_lk.setGeometry(QtCore.QRect(690, 80, 150, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f_lk.setFont(font)
        self.f_lk.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.f_lk.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f_lk.setMinimum(0.01)
        self.f_lk.setMaximum(0.99)
        self.f_lk.setSingleStep(0.01)
        self.f_lk.setProperty("value", 0.99)
        self.f_lk.setObjectName("f_lk")
        self.f_hk = QtWidgets.QDoubleSpinBox(self.fug)
        self.f_hk.setGeometry(QtCore.QRect(690, 130, 150, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f_hk.setFont(font)
        self.f_hk.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.f_hk.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f_hk.setMinimum(0.01)
        self.f_hk.setMaximum(0.99)
        self.f_hk.setSingleStep(0.01)
        self.f_hk.setProperty("value", 0.99)
        self.f_hk.setObjectName("f_hk")
        self.label_9 = QtWidgets.QLabel(self.fug)
        self.label_9.setGeometry(QtCore.QRect(690, 60, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.fug)
        self.label_10.setGeometry(QtCore.QRect(690, 110, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.results_fug = QtWidgets.QTextBrowser(self.fug)
        self.results_fug.setGeometry(QtCore.QRect(170, 370, 561, 221))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.results_fug.setFont(font)
        self.results_fug.setObjectName("results_fug")
        self.label_11 = QtWidgets.QLabel(self.fug)
        self.label_11.setGeometry(QtCore.QRect(170, 340, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.line_5 = QtWidgets.QFrame(self.fug)
        self.line_5.setGeometry(QtCore.QRect(260, 10, 16, 301))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.mole_frac = QtWidgets.QDoubleSpinBox(self.fug)
        self.mole_frac.setGeometry(QtCore.QRect(30, 270, 150, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mole_frac.setFont(font)
        self.mole_frac.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mole_frac.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mole_frac.setDecimals(3)
        self.mole_frac.setMaximum(1.0)
        self.mole_frac.setSingleStep(0.01)
        self.mole_frac.setObjectName("mole_frac")
        self.label_12 = QtWidgets.QLabel(self.fug)
        self.label_12.setGeometry(QtCore.QRect(30, 250, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.stackedWidget.addWidget(self.fug)
        self.mccabe_btn = QtWidgets.QPushButton(self.centralwidget)
        self.mccabe_btn.setGeometry(QtCore.QRect(150, 615, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mccabe_btn.setFont(font)
        self.mccabe_btn.setObjectName("mccabe_btn")
        self.home_btn = QtWidgets.QPushButton(self.centralwidget)
        self.home_btn.setGeometry(QtCore.QRect(413, 615, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_btn.setFont(font)
        self.home_btn.setObjectName("home_btn")
        self.fug_btn = QtWidgets.QPushButton(self.centralwidget)
        self.fug_btn.setGeometry(QtCore.QRect(657, 615, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fug_btn.setFont(font)
        self.fug_btn.setObjectName("fug_btn")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 600, 901, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Métodos de McCabe-Thiele e FUG"))
        self.info.setText(_translate("MainWindow", "TCC 2023A - Vinícius Lermen Spohr"))
        self.radio_btn_parcial.setText(_translate("MainWindow", "Pa/Pb"))
        self.label_23.setText(_translate("MainWindow", "Pa"))
        self.radio_btn_valor.setText(_translate("MainWindow", "Valor"))
        self.btn_ideal.setText(_translate("MainWindow", "Ideal"))
        self.btn_non_ideal.setText(_translate("MainWindow", "Não ideal"))
        self.label_25.setText(_translate("MainWindow", "α"))
        self.label_26.setText(_translate("MainWindow", "Pb"))
        self.label_27.setText(_translate("MainWindow", "xF"))
        self.label_28.setText(_translate("MainWindow", "xB"))
        self.label_29.setText(_translate("MainWindow", "Alimentação"))
        self.label_30.setText(_translate("MainWindow", "R"))
        self.btn_exec.setText(_translate("MainWindow", "Calcular"))
        self.label_31.setText(_translate("MainWindow", "xD"))
        self.label_32.setText(_translate("MainWindow", "q"))
        self.label_33.setText(_translate("MainWindow", "N° estágios"))
        self.label_34.setText(_translate("MainWindow", "Ef. de Murphree"))
        self.save_fig.setText(_translate("MainWindow", "Salvar Figura"))
        self.label.setText(_translate("MainWindow", "Número de componentes"))
        self.hk_rdbtn.setText(_translate("MainWindow", "HK"))
        self.lk_rdbtn.setText(_translate("MainWindow", "LK"))
        self.label_2.setText(_translate("MainWindow", "Selecione"))
        self.label_3.setText(_translate("MainWindow", "Componente"))
        self.preview_btn.setText(_translate("MainWindow", "Pré-visualizar"))
        self.calc_fug_btn.setText(_translate("MainWindow", "CALCULAR"))
        self.label_4.setText(_translate("MainWindow", "Alimentação (mols)"))
        self.label_5.setText(_translate("MainWindow", "Razão de refluxo (R/Rmin)"))
        self.label_6.setText(_translate("MainWindow", "Condição da alimentação (q)"))
        self.label_7.setText(_translate("MainWindow", "Temperatura de fundo (°C)"))
        self.label_8.setText(_translate("MainWindow", "Temperatura de topo (°C)"))
        self.label_9.setText(_translate("MainWindow", "Fração de LK recuperado no topo"))
        self.label_10.setText(_translate("MainWindow", "Fração de HK recuperado no fundo"))
        self.label_11.setText(_translate("MainWindow", "RESULTADOS"))
        self.label_12.setText(_translate("MainWindow", "Fração molar"))
        self.mccabe_btn.setText(_translate("MainWindow", "McCabe-Thiele"))
        self.home_btn.setText(_translate("MainWindow", "Home"))
        self.fug_btn.setText(_translate("MainWindow", "FUG"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
